name: makedocs

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]


jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      # - name: Get GitHub App Installation Access Token
      #   id: token
      #   run: |
      #     # Obtain a token from `dpng-gitops` app, this application has permissions to read private repositories 
      #     TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
      #     echo "::add-mask::$TOKEN"
      #     echo "token=$( echo "$TOKEN" )" >> $GITHUB_OUTPUT
      - name: Dispatch event to main repository
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.token.outputs.token }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/Klarrio/platform-documentation/dispatches \
            -d '{"event_type": "trigger-main-workflow-servicemesh"}'
